name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest # 修改为ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash # 修改为bash，适合Ubuntu环境

  goodbye:
    runs-on: ubuntu-latest # 修改为ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye World"
        shell: bash # 修改为bash，适合Ubuntu环境
